// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BrandDocumentDataSlicesSlice = BrandStorySlice | CallToActionSlice;

/**
 * Content for Brand documents
 */
interface BrandDocumentData {
  /**
   * Slice Zone field in *Brand*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BrandDocumentDataSlicesSlice> /**
   * Meta Title field in *Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: brand.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: brand.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Brand document from Prismic
 *
 * - **API ID**: `brand`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BrandDocumentData>, "brand", Lang>;

type CollectionDocumentDataSlicesSlice = TextSectionSlice | HeroSlice;

/**
 * Content for Collection documents
 */
interface CollectionDocumentData {
  /**
   * Slice Zone field in *Collection*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CollectionDocumentDataSlicesSlice> /**
   * Meta Title field in *Collection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: collection.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Collection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: collection.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Collection*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Collection document from Prismic
 *
 * - **API ID**: `collection`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CollectionDocumentData>,
    "collection",
    Lang
  >;

type FragranceDocumentDataSlicesSlice = never;

/**
 * Content for Fragrance  documents
 */
interface FragranceDocumentData {
  /**
   * Title field in *Fragrance *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fragrance.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Bottle Image field in *Fragrance *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fragrance.bottle_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bottle_image: prismic.ImageField<never>;

  /**
   * Featured Image field in *Fragrance *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fragrance.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Description field in *Fragrance *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fragrance.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Price field in *Fragrance *
   *
   * - **Field Type**: Number
   * - **Placeholder**: (in cents)
   * - **API ID Path**: fragrance.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Scent Profile field in *Fragrance *
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Rare
   * - **API ID Path**: fragrance.scent_profile
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  scent_profile: prismic.SelectField<
    "Rare" | "Bold" | "Vibrant" | "Fresh" | "Woody",
    "filled"
  >;

  /**
   * Mood field in *Fragrance *
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Mystical
   * - **API ID Path**: fragrance.mood
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  mood: prismic.SelectField<
    "Mystical" | "Wise" | "Dynamic" | "Life-giving" | "Trailblazing",
    "filled"
  >;

  /**
   * Energy Type field in *Fragrance *
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Manifestor
   * - **API ID Path**: fragrance.energy_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  energy_type: prismic.SelectField<
    "Manifestor" | "Generator" | "Mani-gen" | "Projector" | "Reflector",
    "filled"
  >;

  /**
   * Gallery Image One field in *Fragrance *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fragrance.gallery_image_one
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gallery_image_one: prismic.ImageField<never>;

  /**
   * Gallery Image Two field in *Fragrance *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fragrance.gallery_image_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gallery_image_two: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Fragrance *
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: fragrance.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FragranceDocumentDataSlicesSlice> /**
   * Meta Image field in *Fragrance *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fragrance.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  meta_image: prismic.ImageField<never>;
}

/**
 * Fragrance  document from Prismic
 *
 * - **API ID**: `fragrance`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FragranceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FragranceDocumentData>,
    "fragrance",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | FullImageSlice
  | VideoSlice
  | CallToActionSlice
  | TextSectionSlice
  | ProductFeatureSlice
  | FeaturedFragranceSlice
  | ScrollTextSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type JournalDocumentDataSlicesSlice = CallToActionSlice;

/**
 * Content for Journal documents
 */
interface JournalDocumentData {
  /**
   * Slice Zone field in *Journal*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: journal.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<JournalDocumentDataSlicesSlice> /**
   * Meta Title field in *Journal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: journal.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Journal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: journal.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Journal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: journal.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Journal document from Prismic
 *
 * - **API ID**: `journal`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JournalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<JournalDocumentData>,
    "journal",
    Lang
  >;

/**
 * Item in *Quiz → Questions*
 */
export interface QuizDocumentDataQuestionsItem {
  /**
   * Question Text field in *Quiz → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].question_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question_text: prismic.KeyTextField;

  /**
   * Image Electra field in *Quiz → Questions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].image_electra
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_electra: prismic.ImageField<never>;

  /**
   * Answer Electra field in *Quiz → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].answer_electra
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer_electra: prismic.KeyTextField;

  /**
   * Image Stargazer field in *Quiz → Questions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].image_stargazer
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_stargazer: prismic.ImageField<never>;

  /**
   * Answer Stargazer field in *Quiz → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].answer_stargazer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer_stargazer: prismic.KeyTextField;

  /**
   * Image Oracle field in *Quiz → Questions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].image_oracle
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_oracle: prismic.ImageField<never>;

  /**
   * Answer Oracle field in *Quiz → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].answer_oracle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer_oracle: prismic.KeyTextField;

  /**
   * Image Reign field in *Quiz → Questions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].image_reign
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_reign: prismic.ImageField<never>;

  /**
   * Answer Reign field in *Quiz → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].answer_reign
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer_reign: prismic.KeyTextField;

  /**
   * Image Luminara field in *Quiz → Questions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].image_luminara
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_luminara: prismic.ImageField<never>;

  /**
   * Answer Luminara field in *Quiz → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[].answer_luminara
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer_luminara: prismic.KeyTextField;
}

type QuizDocumentDataSlicesSlice = never;

/**
 * Content for Quiz documents
 */
interface QuizDocumentData {
  /**
   * Eyebrow field in *Quiz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.eyebrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Quiz*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Quiz*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Start Button Text field in *Quiz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.start_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  start_button_text: prismic.KeyTextField;

  /**
   * Questions field in *Quiz*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.questions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  questions: prismic.GroupField<Simplify<QuizDocumentDataQuestionsItem>>;

  /**
   * Slice Zone field in *Quiz*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<QuizDocumentDataSlicesSlice> /**
   * Meta Title field in *Quiz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: quiz.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Quiz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: quiz.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Quiz*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Quiz document from Prismic
 *
 * - **API ID**: `quiz`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuizDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<QuizDocumentData>, "quiz", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  fallback_og_image: prismic.ImageField<never>;

  /**
   * Navigation Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BrandDocument
  | CollectionDocument
  | FragranceDocument
  | HomepageDocument
  | JournalDocument
  | QuizDocument
  | SettingsDocument;

/**
 * Primary content in *BrandStory → Default → Primary*
 */
export interface BrandStorySliceDefaultPrimary {
  /**
   * Eyebrow field in *BrandStory → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: eyebrow text
   * - **API ID Path**: brand_story.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *BrandStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_story.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *BrandStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_story.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image Side field in *BrandStory → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_story.default.primary.image_side
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_side: prismic.SelectField<"Left" | "Right">;

  /**
   * Image field in *BrandStory → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_story.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Background Color field in *BrandStory → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: brand_story.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<"White" | "Pink" | "Grey", "filled">;
}

/**
 * Default variation for BrandStory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BrandStorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrandStorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BrandStory*
 */
type BrandStorySliceVariation = BrandStorySliceDefault;

/**
 * BrandStory Shared Slice
 *
 * - **API ID**: `brand_story`
 * - **Description**: BrandStory
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BrandStorySlice = prismic.SharedSlice<
  "brand_story",
  BrandStorySliceVariation
>;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Eyebrow field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Button field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Tertiary" | "Link"
  >;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → withVideoBackground → Primary*
 */
export interface CallToActionSliceWithVideoBackgroundPrimary {
  /**
   * Eyebrow field in *CallToAction → withVideoBackground → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.withVideoBackground.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *CallToAction → withVideoBackground → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.withVideoBackground.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *CallToAction → withVideoBackground → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.withVideoBackground.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Button field in *CallToAction → withVideoBackground → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.withVideoBackground.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Tertiary" | "Link"
  >;

  /**
   * YouTube Video ID field in *CallToAction → withVideoBackground → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.withVideoBackground.primary.youtube_video_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  youtube_video_id: prismic.KeyTextField;
}

/**
 * withVideoBackground variation for CallToAction Slice
 *
 * - **API ID**: `withVideoBackground`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceWithVideoBackground = prismic.SharedSliceVariation<
  "withVideoBackground",
  Simplify<CallToActionSliceWithVideoBackgroundPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceWithVideoBackground;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *FeaturedFragrance → Default → Primary*
 */
export interface FeaturedFragranceSliceDefaultPrimary {
  /**
   * Feature Image field in *FeaturedFragrance → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_fragrance.default.primary.feature_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  feature_image: prismic.ImageField<never>;

  /**
   * SmallImage field in *FeaturedFragrance → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_fragrance.default.primary.smallimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  smallimage: prismic.ImageField<never>;

  /**
   * Heading field in *FeaturedFragrance → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_fragrance.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Text field in *FeaturedFragrance → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_fragrance.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Fragrance field in *FeaturedFragrance → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_fragrance.default.primary.fragrance
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  fragrance: ContentRelationshipFieldWithData<
    [{ id: "fragrance"; fields: ["title", "bottle_image", "description"] }]
  >;

  /**
   * Link field in *FeaturedFragrance → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_fragrance.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for FeaturedFragrance Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedFragranceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedFragranceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedFragrance*
 */
type FeaturedFragranceSliceVariation = FeaturedFragranceSliceDefault;

/**
 * FeaturedFragrance Shared Slice
 *
 * - **API ID**: `featured_fragrance`
 * - **Description**: FeaturedFragrance
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedFragranceSlice = prismic.SharedSlice<
  "featured_fragrance",
  FeaturedFragranceSliceVariation
>;

/**
 * Primary content in *FullImage → Default → Primary*
 */
export interface FullImageSliceDefaultPrimary {
  /**
   * Image field in *FullImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *FullImage → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: full_image.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  link: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for FullImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullImage*
 */
type FullImageSliceVariation = FullImageSliceDefault;

/**
 * FullImage Shared Slice
 *
 * - **API ID**: `full_image`
 * - **Description**: FullImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullImageSlice = prismic.SharedSlice<
  "full_image",
  FullImageSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading H1
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Paragraph field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Paragraph
   * - **API ID Path**: hero.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * Button  field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Fragrance field in *Hero → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.fragrance
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  fragrance: prismic.ContentRelationshipField<"fragrance">;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ProductFeature → Default → Primary*
 */
export interface ProductFeatureSliceDefaultPrimary {
  /**
   * LeftImage field in *ProductFeature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_feature.default.primary.leftimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  leftimage: prismic.ImageField<never>;

  /**
   * RightImage field in *ProductFeature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_feature.default.primary.rightimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  rightimage: prismic.ImageField<never>;

  /**
   * Title field in *ProductFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * TextBody field in *ProductFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_feature.default.primary.textbody
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  textbody: prismic.RichTextField;

  /**
   * FeaturedLink field in *ProductFeature → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: product_feature.default.primary.featuredlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  featuredlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Tertiary" | "Link"
  >;
}

/**
 * Default variation for ProductFeature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductFeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductFeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductFeature*
 */
type ProductFeatureSliceVariation = ProductFeatureSliceDefault;

/**
 * ProductFeature Shared Slice
 *
 * - **API ID**: `product_feature`
 * - **Description**: ProductFeature
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductFeatureSlice = prismic.SharedSlice<
  "product_feature",
  ProductFeatureSliceVariation
>;

/**
 * Primary content in *ScrollText → Default → Primary*
 */
export interface ScrollTextSliceDefaultPrimary {
  /**
   * Eyebrow field in *ScrollText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_text.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Text field in *ScrollText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for ScrollText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScrollTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScrollText*
 */
type ScrollTextSliceVariation = ScrollTextSliceDefault;

/**
 * ScrollText Shared Slice
 *
 * - **API ID**: `scroll_text`
 * - **Description**: ScrollText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollTextSlice = prismic.SharedSlice<
  "scroll_text",
  ScrollTextSliceVariation
>;

/**
 * Item in *ListSection → Default → Primary → Fragrances*
 */
export interface TextSectionSliceDefaultPrimaryFragrancesItem {
  /**
   * Fragrance field in *ListSection → Default → Primary → Fragrances*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.fragrances[].fragrance
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  fragrance: prismic.ContentRelationshipField<"fragrance">;
}

/**
 * Primary content in *ListSection → Default → Primary*
 */
export interface TextSectionSliceDefaultPrimary {
  /**
   * Eyebrow field in *ListSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *ListSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ListSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Fragrances field in *ListSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.fragrances[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  fragrances: prismic.GroupField<
    Simplify<TextSectionSliceDefaultPrimaryFragrancesItem>
  >;
}

/**
 * Default variation for ListSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ListSection*
 */
type TextSectionSliceVariation = TextSectionSliceDefault;

/**
 * ListSection Shared Slice
 *
 * - **API ID**: `text_section`
 * - **Description**: TextSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSectionSlice = prismic.SharedSlice<
  "text_section",
  TextSectionSliceVariation
>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * YouTube Video Id field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: eTEsWseiDdg
   * - **API ID Path**: video.default.primary.youtube_video_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  youtube_video_id: prismic.KeyTextField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BrandDocument,
      BrandDocumentData,
      BrandDocumentDataSlicesSlice,
      CollectionDocument,
      CollectionDocumentData,
      CollectionDocumentDataSlicesSlice,
      FragranceDocument,
      FragranceDocumentData,
      FragranceDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      JournalDocument,
      JournalDocumentData,
      JournalDocumentDataSlicesSlice,
      QuizDocument,
      QuizDocumentData,
      QuizDocumentDataQuestionsItem,
      QuizDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      BrandStorySlice,
      BrandStorySliceDefaultPrimary,
      BrandStorySliceVariation,
      BrandStorySliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceWithVideoBackgroundPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceWithVideoBackground,
      FeaturedFragranceSlice,
      FeaturedFragranceSliceDefaultPrimary,
      FeaturedFragranceSliceVariation,
      FeaturedFragranceSliceDefault,
      FullImageSlice,
      FullImageSliceDefaultPrimary,
      FullImageSliceVariation,
      FullImageSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProductFeatureSlice,
      ProductFeatureSliceDefaultPrimary,
      ProductFeatureSliceVariation,
      ProductFeatureSliceDefault,
      ScrollTextSlice,
      ScrollTextSliceDefaultPrimary,
      ScrollTextSliceVariation,
      ScrollTextSliceDefault,
      TextSectionSlice,
      TextSectionSliceDefaultPrimaryFragrancesItem,
      TextSectionSliceDefaultPrimary,
      TextSectionSliceVariation,
      TextSectionSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
