// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  featured_fragrance: dynamic(() => import("./FeaturedFragrance")),
  full_image: dynamic(() => import("./FullImage")),
  hero: dynamic(() => import("./Hero")),
  product_feature: dynamic(() => import("./ProductFeature")),
  scroll_text: dynamic(() => import("./ScrollText")),
  text_section: dynamic(() => import("./ListSection")),
  video: dynamic(() => import("./Video")),
};
